use_frameworks!

target 'CATNavigationController_Example' do
  pod 'CATNavigationController', :path => '../'

  target 'CATNavigationController_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
